/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.11
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marqeta_coreapi_client

import (
	"encoding/json"
)

// checks if the ProgramGatewayFundingSourceModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProgramGatewayFundingSourceModel{}

// ProgramGatewayFundingSourceModel struct for ProgramGatewayFundingSourceModel
type ProgramGatewayFundingSourceModel struct {
	FundingSourceModel
	Name string `json:"name"`
}

// NewProgramGatewayFundingSourceModel instantiates a new ProgramGatewayFundingSourceModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProgramGatewayFundingSourceModel(name string, active bool, createdTime time.Time, isDefaultAccount bool, lastModifiedTime time.Time, token string, type_ string) *ProgramGatewayFundingSourceModel {
	this := ProgramGatewayFundingSourceModel{}
	this.Active = active
	this.CreatedTime = createdTime
	this.IsDefaultAccount = isDefaultAccount
	this.LastModifiedTime = lastModifiedTime
	this.Token = token
	this.Type = type_
	this.Name = name
	return &this
}

// NewProgramGatewayFundingSourceModelWithDefaults instantiates a new ProgramGatewayFundingSourceModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProgramGatewayFundingSourceModelWithDefaults() *ProgramGatewayFundingSourceModel {
	this := ProgramGatewayFundingSourceModel{}
	return &this
}

// GetName returns the Name field value
func (o *ProgramGatewayFundingSourceModel) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ProgramGatewayFundingSourceModel) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ProgramGatewayFundingSourceModel) SetName(v string) {
	o.Name = v
}

func (o ProgramGatewayFundingSourceModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProgramGatewayFundingSourceModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedFundingSourceModel, errFundingSourceModel := json.Marshal(o.FundingSourceModel)
	if errFundingSourceModel != nil {
		return map[string]interface{}{}, errFundingSourceModel
	}
	errFundingSourceModel = json.Unmarshal([]byte(serializedFundingSourceModel), &toSerialize)
	if errFundingSourceModel != nil {
		return map[string]interface{}{}, errFundingSourceModel
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

type NullableProgramGatewayFundingSourceModel struct {
	value *ProgramGatewayFundingSourceModel
	isSet bool
}

func (v NullableProgramGatewayFundingSourceModel) Get() *ProgramGatewayFundingSourceModel {
	return v.value
}

func (v *NullableProgramGatewayFundingSourceModel) Set(val *ProgramGatewayFundingSourceModel) {
	v.value = val
	v.isSet = true
}

func (v NullableProgramGatewayFundingSourceModel) IsSet() bool {
	return v.isSet
}

func (v *NullableProgramGatewayFundingSourceModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProgramGatewayFundingSourceModel(val *ProgramGatewayFundingSourceModel) *NullableProgramGatewayFundingSourceModel {
	return &NullableProgramGatewayFundingSourceModel{value: val, isSet: true}
}

func (v NullableProgramGatewayFundingSourceModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProgramGatewayFundingSourceModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


