/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.11
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreapi

import (
	"encoding/json"
)

// checks if the CardOptionsBillingAddress type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CardOptionsBillingAddress{}

// CardOptionsBillingAddress Used for AVS (address verification system). The address-related fields in this object are verified against known values.
type CardOptionsBillingAddress struct {
	// Cardholder's first name.
	FirstName *string `json:"first_name,omitempty"`
	// Cardholder's last name.
	LastName *string `json:"last_name,omitempty"`
	// Cardholder's address.
	Address *string `json:"address,omitempty"`
	// Cardholder's postal code.
	Zip *string `json:"zip,omitempty"`
}

// NewCardOptionsBillingAddress instantiates a new CardOptionsBillingAddress object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCardOptionsBillingAddress() *CardOptionsBillingAddress {
	this := CardOptionsBillingAddress{}
	return &this
}

// NewCardOptionsBillingAddressWithDefaults instantiates a new CardOptionsBillingAddress object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCardOptionsBillingAddressWithDefaults() *CardOptionsBillingAddress {
	this := CardOptionsBillingAddress{}
	return &this
}

// GetFirstName returns the FirstName field value if set, zero value otherwise.
func (o *CardOptionsBillingAddress) GetFirstName() string {
	if o == nil || IsNil(o.FirstName) {
		var ret string
		return ret
	}
	return *o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardOptionsBillingAddress) GetFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.FirstName) {
		return nil, false
	}
	return o.FirstName, true
}

// HasFirstName returns a boolean if a field has been set.
func (o *CardOptionsBillingAddress) HasFirstName() bool {
	if o != nil && !IsNil(o.FirstName) {
		return true
	}

	return false
}

// SetFirstName gets a reference to the given string and assigns it to the FirstName field.
func (o *CardOptionsBillingAddress) SetFirstName(v string) {
	o.FirstName = &v
}

// GetLastName returns the LastName field value if set, zero value otherwise.
func (o *CardOptionsBillingAddress) GetLastName() string {
	if o == nil || IsNil(o.LastName) {
		var ret string
		return ret
	}
	return *o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardOptionsBillingAddress) GetLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.LastName) {
		return nil, false
	}
	return o.LastName, true
}

// HasLastName returns a boolean if a field has been set.
func (o *CardOptionsBillingAddress) HasLastName() bool {
	if o != nil && !IsNil(o.LastName) {
		return true
	}

	return false
}

// SetLastName gets a reference to the given string and assigns it to the LastName field.
func (o *CardOptionsBillingAddress) SetLastName(v string) {
	o.LastName = &v
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *CardOptionsBillingAddress) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardOptionsBillingAddress) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *CardOptionsBillingAddress) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *CardOptionsBillingAddress) SetAddress(v string) {
	o.Address = &v
}

// GetZip returns the Zip field value if set, zero value otherwise.
func (o *CardOptionsBillingAddress) GetZip() string {
	if o == nil || IsNil(o.Zip) {
		var ret string
		return ret
	}
	return *o.Zip
}

// GetZipOk returns a tuple with the Zip field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CardOptionsBillingAddress) GetZipOk() (*string, bool) {
	if o == nil || IsNil(o.Zip) {
		return nil, false
	}
	return o.Zip, true
}

// HasZip returns a boolean if a field has been set.
func (o *CardOptionsBillingAddress) HasZip() bool {
	if o != nil && !IsNil(o.Zip) {
		return true
	}

	return false
}

// SetZip gets a reference to the given string and assigns it to the Zip field.
func (o *CardOptionsBillingAddress) SetZip(v string) {
	o.Zip = &v
}

func (o CardOptionsBillingAddress) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CardOptionsBillingAddress) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.FirstName) {
		toSerialize["first_name"] = o.FirstName
	}
	if !IsNil(o.LastName) {
		toSerialize["last_name"] = o.LastName
	}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Zip) {
		toSerialize["zip"] = o.Zip
	}
	return toSerialize, nil
}

type NullableCardOptionsBillingAddress struct {
	value *CardOptionsBillingAddress
	isSet bool
}

func (v NullableCardOptionsBillingAddress) Get() *CardOptionsBillingAddress {
	return v.value
}

func (v *NullableCardOptionsBillingAddress) Set(val *CardOptionsBillingAddress) {
	v.value = val
	v.isSet = true
}

func (v NullableCardOptionsBillingAddress) IsSet() bool {
	return v.isSet
}

func (v *NullableCardOptionsBillingAddress) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCardOptionsBillingAddress(val *CardOptionsBillingAddress) *NullableCardOptionsBillingAddress {
	return &NullableCardOptionsBillingAddress{value: val, isSet: true}
}

func (v NullableCardOptionsBillingAddress) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCardOptionsBillingAddress) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


