/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.11
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marqeta_coreapi_client

import (
	"encoding/json"
)

// checks if the OriginalCreditAuthPlusCaptureReversalEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &OriginalCreditAuthPlusCaptureReversalEvent{}

// OriginalCreditAuthPlusCaptureReversalEvent struct for OriginalCreditAuthPlusCaptureReversalEvent
type OriginalCreditAuthPlusCaptureReversalEvent struct {
	CardTransactionSimulation
	// Unique identifier of the card. Useful when a single account holder has multiple cards.
	PrecedingRelatedTransactionToken string `json:"preceding_related_transaction_token"`
	// Amount of the transaction.
	Amount float32 `json:"amount"`
	CardAcceptor *TransactionCardAcceptor `json:"card_acceptor,omitempty"`
}

// NewOriginalCreditAuthPlusCaptureReversalEvent instantiates a new OriginalCreditAuthPlusCaptureReversalEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewOriginalCreditAuthPlusCaptureReversalEvent(precedingRelatedTransactionToken string, amount float32) *OriginalCreditAuthPlusCaptureReversalEvent {
	this := OriginalCreditAuthPlusCaptureReversalEvent{}
	var isPreauthorization bool = false
	this.IsPreauthorization = &isPreauthorization
	var forcePost bool = false
	this.ForcePost = &forcePost
	return &this
}

// NewOriginalCreditAuthPlusCaptureReversalEventWithDefaults instantiates a new OriginalCreditAuthPlusCaptureReversalEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewOriginalCreditAuthPlusCaptureReversalEventWithDefaults() *OriginalCreditAuthPlusCaptureReversalEvent {
	this := OriginalCreditAuthPlusCaptureReversalEvent{}
	return &this
}

// GetPrecedingRelatedTransactionToken returns the PrecedingRelatedTransactionToken field value
func (o *OriginalCreditAuthPlusCaptureReversalEvent) GetPrecedingRelatedTransactionToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PrecedingRelatedTransactionToken
}

// GetPrecedingRelatedTransactionTokenOk returns a tuple with the PrecedingRelatedTransactionToken field value
// and a boolean to check if the value has been set.
func (o *OriginalCreditAuthPlusCaptureReversalEvent) GetPrecedingRelatedTransactionTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PrecedingRelatedTransactionToken, true
}

// SetPrecedingRelatedTransactionToken sets field value
func (o *OriginalCreditAuthPlusCaptureReversalEvent) SetPrecedingRelatedTransactionToken(v string) {
	o.PrecedingRelatedTransactionToken = v
}

// GetAmount returns the Amount field value
func (o *OriginalCreditAuthPlusCaptureReversalEvent) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *OriginalCreditAuthPlusCaptureReversalEvent) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *OriginalCreditAuthPlusCaptureReversalEvent) SetAmount(v float32) {
	o.Amount = v
}

// GetCardAcceptor returns the CardAcceptor field value if set, zero value otherwise.
func (o *OriginalCreditAuthPlusCaptureReversalEvent) GetCardAcceptor() TransactionCardAcceptor {
	if o == nil || IsNil(o.CardAcceptor) {
		var ret TransactionCardAcceptor
		return ret
	}
	return *o.CardAcceptor
}

// GetCardAcceptorOk returns a tuple with the CardAcceptor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *OriginalCreditAuthPlusCaptureReversalEvent) GetCardAcceptorOk() (*TransactionCardAcceptor, bool) {
	if o == nil || IsNil(o.CardAcceptor) {
		return nil, false
	}
	return o.CardAcceptor, true
}

// HasCardAcceptor returns a boolean if a field has been set.
func (o *OriginalCreditAuthPlusCaptureReversalEvent) HasCardAcceptor() bool {
	if o != nil && !IsNil(o.CardAcceptor) {
		return true
	}

	return false
}

// SetCardAcceptor gets a reference to the given TransactionCardAcceptor and assigns it to the CardAcceptor field.
func (o *OriginalCreditAuthPlusCaptureReversalEvent) SetCardAcceptor(v TransactionCardAcceptor) {
	o.CardAcceptor = &v
}

func (o OriginalCreditAuthPlusCaptureReversalEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o OriginalCreditAuthPlusCaptureReversalEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	serializedCardTransactionSimulation, errCardTransactionSimulation := json.Marshal(o.CardTransactionSimulation)
	if errCardTransactionSimulation != nil {
		return map[string]interface{}{}, errCardTransactionSimulation
	}
	errCardTransactionSimulation = json.Unmarshal([]byte(serializedCardTransactionSimulation), &toSerialize)
	if errCardTransactionSimulation != nil {
		return map[string]interface{}{}, errCardTransactionSimulation
	}
	toSerialize["preceding_related_transaction_token"] = o.PrecedingRelatedTransactionToken
	toSerialize["amount"] = o.Amount
	if !IsNil(o.CardAcceptor) {
		toSerialize["card_acceptor"] = o.CardAcceptor
	}
	return toSerialize, nil
}

type NullableOriginalCreditAuthPlusCaptureReversalEvent struct {
	value *OriginalCreditAuthPlusCaptureReversalEvent
	isSet bool
}

func (v NullableOriginalCreditAuthPlusCaptureReversalEvent) Get() *OriginalCreditAuthPlusCaptureReversalEvent {
	return v.value
}

func (v *NullableOriginalCreditAuthPlusCaptureReversalEvent) Set(val *OriginalCreditAuthPlusCaptureReversalEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableOriginalCreditAuthPlusCaptureReversalEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableOriginalCreditAuthPlusCaptureReversalEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableOriginalCreditAuthPlusCaptureReversalEvent(val *OriginalCreditAuthPlusCaptureReversalEvent) *NullableOriginalCreditAuthPlusCaptureReversalEvent {
	return &NullableOriginalCreditAuthPlusCaptureReversalEvent{value: val, isSet: true}
}

func (v NullableOriginalCreditAuthPlusCaptureReversalEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableOriginalCreditAuthPlusCaptureReversalEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


