/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.11
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreapi

import (
	"encoding/json"
)

// checks if the RequestForWppParameters type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RequestForWppParameters{}

// RequestForWppParameters struct for RequestForWppParameters
type RequestForWppParameters struct {
	// Unique identifier of the card resource.
	CardToken string `json:"card_token"`
}

// NewRequestForWppParameters instantiates a new RequestForWppParameters object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRequestForWppParameters(cardToken string) *RequestForWppParameters {
	this := RequestForWppParameters{}
	this.CardToken = cardToken
	return &this
}

// NewRequestForWppParametersWithDefaults instantiates a new RequestForWppParameters object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRequestForWppParametersWithDefaults() *RequestForWppParameters {
	this := RequestForWppParameters{}
	return &this
}

// GetCardToken returns the CardToken field value
func (o *RequestForWppParameters) GetCardToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CardToken
}

// GetCardTokenOk returns a tuple with the CardToken field value
// and a boolean to check if the value has been set.
func (o *RequestForWppParameters) GetCardTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CardToken, true
}

// SetCardToken sets field value
func (o *RequestForWppParameters) SetCardToken(v string) {
	o.CardToken = v
}

func (o RequestForWppParameters) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RequestForWppParameters) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["card_token"] = o.CardToken
	return toSerialize, nil
}

type NullableRequestForWppParameters struct {
	value *RequestForWppParameters
	isSet bool
}

func (v NullableRequestForWppParameters) Get() *RequestForWppParameters {
	return v.value
}

func (v *NullableRequestForWppParameters) Set(val *RequestForWppParameters) {
	v.value = val
	v.isSet = true
}

func (v NullableRequestForWppParameters) IsSet() bool {
	return v.isSet
}

func (v *NullableRequestForWppParameters) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRequestForWppParameters(val *RequestForWppParameters) *NullableRequestForWppParameters {
	return &NullableRequestForWppParameters{value: val, isSet: true}
}

func (v NullableRequestForWppParameters) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRequestForWppParameters) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


