/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.11
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package marqeta_coreapi_client

import (
	"encoding/json"
)

// checks if the ResetUserPasswordEmailModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResetUserPasswordEmailModel{}

// ResetUserPasswordEmailModel struct for ResetUserPasswordEmailModel
type ResetUserPasswordEmailModel struct {
	// Cardholder email address.
	Email string `json:"email"`
}

// NewResetUserPasswordEmailModel instantiates a new ResetUserPasswordEmailModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResetUserPasswordEmailModel(email string) *ResetUserPasswordEmailModel {
	this := ResetUserPasswordEmailModel{}
	this.Email = email
	return &this
}

// NewResetUserPasswordEmailModelWithDefaults instantiates a new ResetUserPasswordEmailModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResetUserPasswordEmailModelWithDefaults() *ResetUserPasswordEmailModel {
	this := ResetUserPasswordEmailModel{}
	return &this
}

// GetEmail returns the Email field value
func (o *ResetUserPasswordEmailModel) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *ResetUserPasswordEmailModel) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *ResetUserPasswordEmailModel) SetEmail(v string) {
	o.Email = v
}

func (o ResetUserPasswordEmailModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResetUserPasswordEmailModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	return toSerialize, nil
}

type NullableResetUserPasswordEmailModel struct {
	value *ResetUserPasswordEmailModel
	isSet bool
}

func (v NullableResetUserPasswordEmailModel) Get() *ResetUserPasswordEmailModel {
	return v.value
}

func (v *NullableResetUserPasswordEmailModel) Set(val *ResetUserPasswordEmailModel) {
	v.value = val
	v.isSet = true
}

func (v NullableResetUserPasswordEmailModel) IsSet() bool {
	return v.isSet
}

func (v *NullableResetUserPasswordEmailModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResetUserPasswordEmailModel(val *ResetUserPasswordEmailModel) *NullableResetUserPasswordEmailModel {
	return &NullableResetUserPasswordEmailModel{value: val, isSet: true}
}

func (v NullableResetUserPasswordEmailModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResetUserPasswordEmailModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


