/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.11
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreapi

import (
	"encoding/json"
)

// checks if the WebhookPingModel type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &WebhookPingModel{}

// WebhookPingModel struct for WebhookPingModel
type WebhookPingModel struct {
	// Array of ping requests to your webhook endpoint.
	Pings []EchoPingRequest `json:"pings"`
}

// NewWebhookPingModel instantiates a new WebhookPingModel object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWebhookPingModel(pings []EchoPingRequest) *WebhookPingModel {
	this := WebhookPingModel{}
	this.Pings = pings
	return &this
}

// NewWebhookPingModelWithDefaults instantiates a new WebhookPingModel object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWebhookPingModelWithDefaults() *WebhookPingModel {
	this := WebhookPingModel{}
	return &this
}

// GetPings returns the Pings field value
func (o *WebhookPingModel) GetPings() []EchoPingRequest {
	if o == nil {
		var ret []EchoPingRequest
		return ret
	}

	return o.Pings
}

// GetPingsOk returns a tuple with the Pings field value
// and a boolean to check if the value has been set.
func (o *WebhookPingModel) GetPingsOk() ([]EchoPingRequest, bool) {
	if o == nil {
		return nil, false
	}
	return o.Pings, true
}

// SetPings sets field value
func (o *WebhookPingModel) SetPings(v []EchoPingRequest) {
	o.Pings = v
}

func (o WebhookPingModel) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o WebhookPingModel) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["pings"] = o.Pings
	return toSerialize, nil
}

type NullableWebhookPingModel struct {
	value *WebhookPingModel
	isSet bool
}

func (v NullableWebhookPingModel) Get() *WebhookPingModel {
	return v.value
}

func (v *NullableWebhookPingModel) Set(val *WebhookPingModel) {
	v.value = val
	v.isSet = true
}

func (v NullableWebhookPingModel) IsSet() bool {
	return v.isSet
}

func (v *NullableWebhookPingModel) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWebhookPingModel(val *WebhookPingModel) *NullableWebhookPingModel {
	return &NullableWebhookPingModel{value: val, isSet: true}
}

func (v NullableWebhookPingModel) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWebhookPingModel) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


