/*
Core API

Marqeta's Core API endpoints, conveniently annotated to enable code generation (including SDKs), test cases, and documentation. Currently in beta.

API version: 3.0.11
Contact: support@marqeta.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package coreapi

import (
	"encoding/json"
)

// checks if the DDARequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &DDARequest{}

// DDARequest struct for DDARequest
type DDARequest struct {
	Dda string `json:"dda"`
}

// NewDDARequest instantiates a new DDARequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDDARequest(dda string) *DDARequest {
	this := DDARequest{}
	this.Dda = dda
	return &this
}

// NewDDARequestWithDefaults instantiates a new DDARequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDDARequestWithDefaults() *DDARequest {
	this := DDARequest{}
	return &this
}

// GetDda returns the Dda field value
func (o *DDARequest) GetDda() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Dda
}

// GetDdaOk returns a tuple with the Dda field value
// and a boolean to check if the value has been set.
func (o *DDARequest) GetDdaOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Dda, true
}

// SetDda sets field value
func (o *DDARequest) SetDda(v string) {
	o.Dda = v
}

func (o DDARequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o DDARequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["dda"] = o.Dda
	return toSerialize, nil
}

type NullableDDARequest struct {
	value *DDARequest
	isSet bool
}

func (v NullableDDARequest) Get() *DDARequest {
	return v.value
}

func (v *NullableDDARequest) Set(val *DDARequest) {
	v.value = val
	v.isSet = true
}

func (v NullableDDARequest) IsSet() bool {
	return v.isSet
}

func (v *NullableDDARequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDDARequest(val *DDARequest) *NullableDDARequest {
	return &NullableDDARequest{value: val, isSet: true}
}

func (v NullableDDARequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDDARequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


